/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuTableRouteImport } from './routes/menu.$table'
import { Route as FoodIdRouteImport } from './routes/food.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuTableRoute = MenuTableRouteImport.update({
  id: '/$table',
  path: '/$table',
  getParentRoute: () => MenuRoute,
} as any)
const FoodIdRoute = FoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/feedback': typeof FeedbackRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reception': typeof ReceptionRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/food/$id': typeof FoodIdRoute
  '/menu/$table': typeof MenuTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/feedback': typeof FeedbackRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reception': typeof ReceptionRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/food/$id': typeof FoodIdRoute
  '/menu/$table': typeof MenuTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/feedback': typeof FeedbackRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reception': typeof ReceptionRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/food/$id': typeof FoodIdRoute
  '/menu/$table': typeof MenuTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/feedback'
    | '/kitchen'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/payment'
    | '/profile'
    | '/reception'
    | '/services'
    | '/track'
    | '/food/$id'
    | '/menu/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/feedback'
    | '/kitchen'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/payment'
    | '/profile'
    | '/reception'
    | '/services'
    | '/track'
    | '/food/$id'
    | '/menu/$table'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/feedback'
    | '/kitchen'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/payment'
    | '/profile'
    | '/reception'
    | '/services'
    | '/track'
    | '/food/$id'
    | '/menu/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  FeedbackRoute: typeof FeedbackRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  ReceptionRoute: typeof ReceptionRoute
  ServicesRoute: typeof ServicesRoute
  TrackRoute: typeof TrackRoute
  FoodIdRoute: typeof FoodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$table': {
      id: '/menu/$table'
      path: '/$table'
      fullPath: '/menu/$table'
      preLoaderRoute: typeof MenuTableRouteImport
      parentRoute: typeof MenuRoute
    }
    '/food/$id': {
      id: '/food/$id'
      path: '/food/$id'
      fullPath: '/food/$id'
      preLoaderRoute: typeof FoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MenuRouteChildren {
  MenuTableRoute: typeof MenuTableRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuTableRoute: MenuTableRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  FeedbackRoute: FeedbackRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  ReceptionRoute: ReceptionRoute,
  ServicesRoute: ServicesRoute,
  TrackRoute: TrackRoute,
  FoodIdRoute: FoodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
